### ISSUE TITLE
Invalid stage identifier specified

### ISSUE THREAD

**Issue by Pavel910** [serverless-components/domain#8]
When trying to deploy a domain from my custom component I encountered this error:

```
  error:
  Error: BadRequestException: Invalid stage identifier specified
    at deployApiDomain (/Users/paveldenisjuk/webiny/js/webiny-js/node_modules/@serverless/domain/utils.js:378:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  23s › api › Error: BadRequestException: Invalid stage identifier specified
```

It is caused by a hardcoded stage `production` at this line: 
`https://github.com/serverless-components/domain/blob/master/utils.js#L328`

When you change it to `prod`, the problem goes away, however the problem is - it is hardcoded, and when I deploy my API Gateway with input parameter of `stage: dev` it does not get forwarded to the path mapping.

**Comment by MarkOnDuty** [comment]
I think that I'm getting hit by the same problem. Here's the error:

```
  Error: BadRequestException: Invalid stage identifier specified
    at deployApiDomain (/home/markfox/.serverless/components/registry/npm/@serverless/domain@6.1.0/node_modules/@serverless/domain/utils.js:387:11)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

  34s › domain › Error: BadRequestException: Invalid stage identifier specified
```
I'm trying to modify the backend-services template example to sit behind a domain, and hit a wall when trying to get the domain working.

Here is my serverless.yml:
```
name: backend-microservices

domain:
  component: '@serverless/domain'
  inputs:
    privateZone: false
    domain: blah.com
    subdomains:
      api: ${restApi}

createUser:
  component: '@serverless/function'
  inputs:
    code: ./src
    handler: index.createUser

getUser:
  component: '@serverless/function'
  inputs:
    code: ./src
    handler: index.getUser

auth:
  component: '@serverless/function'
  inputs:
    code: ./src
    handler: index.auth

restApi:
  component: '@serverless/api'
  inputs:
    endpoints:
      - path: /users
        method: POST
        function: ${createUser}
        authorizer: ${auth}
      - path: /users
        method: GET
        function: ${getUser}
        authorizer: ${auth}
```
